#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0")

'$(basename "$0")' downloads the audio of every video file specified in urls.txt.
The latter file must exist in the current working directory and must contain a URL
on every line.
DOCSTRING
}

checkForHelp $1

cat urls.txt | xargs -I{} dl-audio "{}"
