#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") URL
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

youtube-dl --no-mtime -o "%(upload_date)s %(title)s.%(ext)s" "$1"
