#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") URL
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

require yt-dlp

yt-dlp -f 'bv*[height<=1080]+ba/b[height<=1080]' -i --no-mtime --restrict-filenames -o "$(ytdl-formatstring)" "$@"

