#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") CHANNEL_URL
This script retireves the urls of all videos on a given
Youtube channel and prints them on stdout.
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

require yt-dlp
require jq

yt-dlp --dump-json --ignore-errors "$1" | jq -r '"\(.webpage_url)"'
